services:
  app:
    build: .
    volumes:
      - .:/app
      - sqlite_data:/data
    environment:
      - DATABASE_PATH=/data/mydatabase.db
      - PYTHONPATH=/app
    ports:
      - "8000:8000"
    command: ["uvicorn", "rest_server:app", "--host", "0.0.0.0", "--port", "8000"]

volumes:
  sqlite_data:
